/**
 * SVG Export Service
 *
 * Handles exporting diagrams to SVG format using html-to-image's toSvg function.
 * SVG export provides vector quality output that is infinitely scalable.
 *
 * Note: The generated SVG uses foreignObject to embed HTML content, which
 * preserves the exact appearance of the diagram. The SVG can be opened in
 * browsers, Inkscape, Adobe Illustrator, and other vector graphics editors.
 */

import { toSvg } from 'html-to-image';

/**
 * SVG Export Options
 */
export interface SVGExportOptions {
  /** Background color (default: transparent) */
  backgroundColor?: string;

  /** Output filename (without extension) */
  filename?: string;

  /** Cache busting for external images */
  cacheBust?: boolean;

  /** Custom width (overrides auto-detection) */
  width?: number;

  /** Custom height (overrides auto-detection) */
  height?: number;

  /** Padding around the diagram (in pixels) */
  padding?: number;

  /** Quality of the SVG (for embedded images) */
  quality?: number;

  /** Whether to embed external images as base64 */
  embedImages?: boolean;

  /** Whether to include CSS styles inline */
  inlineStyles?: boolean;

  /** Whether to add metadata comments to the SVG */
  includeMetadata?: boolean;
}

/**
 * SVG Export Result
 */
export interface SVGExportResult {
  /** The SVG string */
  svgString: string;

  /** The Blob of the exported SVG */
  blob: Blob;

  /** The filename used */
  filename: string;

  /** The dimensions of the exported SVG */
  width: number;
  height: number;
}

/**
 * Default SVG export options
 */
export const defaultSVGOptions: SVGExportOptions = {
  backgroundColor: 'transparent',
  cacheBust: true,
  padding: 20,
  quality: 1,
  embedImages: true,
  inlineStyles: true,
  includeMetadata: true,
};

/**
 * Generates a safe filename from a string
 *
 * @param name - The name to sanitize
 * @returns Safe filename
 */
const sanitizeFilename = (name: string): string => {
  return name
    .replace(/[<>:"/\\|?*]/g, '')
    .replace(/\s+/g, '-')
    .substring(0, 200);
};

/**
 * Gets the actual React Flow canvas element from a wrapper
 *
 * @param wrapper - The wrapper element containing React Flow
 * @returns The React Flow canvas element or null
 */
const getReactFlowCanvas = (wrapper: HTMLElement): HTMLElement | null => {
  // React Flow renders a div with class "react-flow" inside the wrapper
  return wrapper.querySelector('.react-flow') as HTMLElement;
};

/**
 * Calculates the bounding box of all nodes in the diagram
 *
 * @param element - The React Flow canvas element
 * @param padding - Padding around the diagram
 * @returns Bounding box with padding
 */
const calculateDiagramBounds = (
  element: HTMLElement,
  padding: number = 20
): { width: number; height: number; x: number; y: number } => {
  const nodes = element.querySelectorAll('.react-flow__node');
  if (nodes.length === 0) {
    return {
      width: element.offsetWidth + padding * 2,
      height: element.offsetHeight + padding * 2,
      x: 0,
      y: 0,
    };
  }

  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  nodes.forEach((node) => {
    const rect = node.getBoundingClientRect();
    const canvasRect = element.getBoundingClientRect();

    // Calculate position relative to canvas
    const x = rect.left - canvasRect.left;
    const y = rect.top - canvasRect.top;

    minX = Math.min(minX, x);
    minY = Math.min(minY, y);
    maxX = Math.max(maxX, x + rect.width);
    maxY = Math.max(maxY, y + rect.height);
  });

  return {
    width: maxX - minX + padding * 2,
    height: maxY - minY + padding * 2,
    x: Math.max(0, minX - padding),
    y: Math.max(0, minY - padding),
  };
};

/**
 * Post-processes the SVG string to improve compatibility
 *
 * @param svgString - The raw SVG string from html-to-image
 * @param options - Export options
 * @returns Processed SVG string
 */
const postProcessSVG = (
  svgString: string,
  options: SVGExportOptions
): string => {
  let processed = svgString;

  // Ensure proper XML declaration
  if (!processed.startsWith('<?xml')) {
    processed = '<?xml version="1.0" encoding="UTF-8"?>\n' + processed;
  }

  // Add metadata comment if requested
  if (options.includeMetadata) {
    const metadata = `<!--
  Generated by Custom Architecture Platform
  Exported: ${new Date().toISOString()}
-->`;
    processed = metadata + '\n' + processed;
  }

  // Ensure xmlns attributes are present
  if (!processed.includes('xmlns="http://www.w3.org/2000/svg"')) {
    processed = processed.replace('<svg', '<svg xmlns="http://www.w3.org/2000/svg"');
  }

  // Add xmlns for XHTML if foreignObject is used
  if (processed.includes('foreignObject') && !processed.includes('xmlns:xhtml')) {
    processed = processed.replace(
      '<svg',
      '<svg xmlns:xhtml="http://www.w3.org/1999/xhtml"'
    );
  }

  // Fix style escaping issues
  processed = processed
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&');

  return processed;
};

/**
 * Exports a diagram element to SVG
 *
 * @param element - The HTML element to export (wrapper or canvas)
 * @param options - Export options
 * @returns Promise resolving to export result
 */
export async function exportAsSVG(
  element: HTMLElement,
  options: SVGExportOptions = {}
): Promise<SVGExportResult> {
  const mergedOptions = { ...defaultSVGOptions, ...options };
  const {
    backgroundColor = 'transparent',
    filename = 'diagram',
    cacheBust = true,
    width,
    height,
    padding = 20,
    quality = 1,
  } = mergedOptions;

  // Get the actual React Flow canvas if a wrapper was provided
  let targetElement = element;
  const canvasElement = getReactFlowCanvas(element);
  if (canvasElement) {
    targetElement = canvasElement;
  }

  // Calculate dimensions if not provided
  const bounds = calculateDiagramBounds(targetElement, padding);
  const exportWidth = width || bounds.width;
  const exportHeight = height || bounds.height;

  // Store original styles
  const originalStyle = targetElement.getAttribute('style');

  try {
    // Handle background color
    const bgElement = targetElement.querySelector('.react-flow__background') as HTMLElement;
    const originalBg = bgElement?.style.background;
    const originalBgColor = bgElement?.style.backgroundColor;

    if (bgElement && backgroundColor !== 'transparent') {
      bgElement.style.background = backgroundColor;
      bgElement.style.backgroundColor = backgroundColor;
    }

    // Add a temporary background overlay if needed
    let overlay: HTMLDivElement | null = null;
    if (backgroundColor !== 'transparent') {
      overlay = document.createElement('div');
      overlay.style.position = 'absolute';
      overlay.style.top = '0';
      overlay.style.left = '0';
      overlay.style.width = '100%';
      overlay.style.height = '100%';
      overlay.style.backgroundColor = backgroundColor;
      overlay.style.zIndex = '-1';
      targetElement.insertBefore(overlay, targetElement.firstChild);
    }

    // Generate SVG data URL
    const dataUrl = await toSvg(targetElement, {
      width: exportWidth,
      height: exportHeight,
      quality,
      cacheBust,
      backgroundColor,
      style: {
        transform: 'none',
        transformOrigin: 'top left',
      },
    });

    // Remove overlay if created
    if (overlay) {
      targetElement.removeChild(overlay);
    }

    // Restore original background
    if (bgElement) {
      if (originalBg !== undefined) {
        bgElement.style.background = originalBg;
      }
      if (originalBgColor !== undefined) {
        bgElement.style.backgroundColor = originalBgColor;
      }
    }

    // Extract SVG string from data URL
    const svgString = dataUrl.replace(/^data:image\/svg\+xml;base64,/, '');
    let decodedSvgString;

    // Try to decode base64, fallback if already decoded
    try {
      decodedSvgString = atob(svgString);
    } catch {
      decodedSvgString = svgString;
    }

    // Post-process the SVG
    const processedSvg = postProcessSVG(decodedSvgString, mergedOptions);

    // Create blob
    const blob = new Blob([processedSvg], {
      type: 'image/svg+xml;charset=utf-8',
    });

    // Generate safe filename
    const safeFilename = sanitizeFilename(filename);
    const fullFilename = `${safeFilename}.svg`;

    return {
      svgString: processedSvg,
      blob,
      filename: fullFilename,
      width: exportWidth,
      height: exportHeight,
    };
  } catch (error) {
    throw new Error(
      `Failed to export diagram as SVG: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  } finally {
    // Restore original style if it was modified
    if (originalStyle !== null) {
      targetElement.setAttribute('style', originalStyle);
    }
  }
}

/**
 * Exports a diagram and triggers a file download
 *
 * @param element - The HTML element to export
 * @param options - Export options
 * @returns Promise resolving when download is triggered
 */
export async function exportAndDownloadSVG(
  element: HTMLElement,
  options: SVGExportOptions = {}
): Promise<void> {
  try {
    const result = await exportAsSVG(element, options);

    // Create download link
    const link = document.createElement('a');
    link.href = URL.createObjectURL(result.blob);
    link.download = result.filename;
    link.style.display = 'none';

    // Trigger download
    document.body.appendChild(link);
    link.click();

    // Cleanup
    setTimeout(() => {
      document.body.removeChild(link);
      URL.revokeObjectURL(link.href);
    }, 100);
  } catch (error) {
    throw new Error(
      `Failed to download SVG: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}

/**
 * Exports a diagram to SVG with progress indication
 * Useful for large diagrams with many nodes
 *
 * @param element - The HTML element to export
 * @param options - Export options
 * @returns Promise resolving to export result
 */
export async function exportAsSVGWithProgress(
  element: HTMLElement,
  options: SVGExportOptions = {}
): Promise<SVGExportResult> {
  const { onProgress, showProgress = true } = options;

  // Show initial progress
  if (showProgress && onProgress) {
    onProgress(0);
  }

  // Simulate progress (html-to-image doesn't provide real progress)
  const progressInterval = onProgress
    ? setInterval(() => {
        onProgress(Math.random() * 50); // 0-50% during processing
      }, 100)
    : null;

  try {
    const result = await exportAsSVG(element, options);

    if (progressInterval) {
      clearInterval(progressInterval);
    }

    if (showProgress && onProgress) {
      onProgress(100);
    }

    return result;
  } catch (error) {
    if (progressInterval) {
      clearInterval(progressInterval);
    }
    throw error;
  }
}

/**
 * Creates a pure SVG representation from nodes and edges
 * This is an alternative method that creates actual SVG elements
 * instead of using foreignObject with HTML.
 *
 * Note: This is a simplified version. For full custom HTML content,
 * use exportAsSVG which preserves the exact rendering.
 *
 * @param nodes - Array of React Flow nodes
 * @param edges - Array of React Flow edges
 * @param options - Export options
 * @returns SVG string
 */
export function createPureSVGFromElements(
  nodes: any[],
  edges: any[],
  options: SVGExportOptions = {}
): string {
  const {
    backgroundColor = 'transparent',
    width = 800,
    height = 600,
    padding = 20,
  } = options;

  // Calculate bounds from nodes
  let minX = Infinity,
    minY = Infinity,
    maxX = -Infinity,
    maxY = -Infinity;

  nodes.forEach((node) => {
    const x = node.position?.x || 0;
    const y = node.position?.y || 0;
    const w = node.width || 200;
    const h = node.height || 100;

    minX = Math.min(minX, x);
    minY = Math.min(minY, y);
    maxX = Math.max(maxX, x + w);
    maxY = Math.max(maxY, y + h);
  });

  const actualWidth = maxX - minX + padding * 2;
  const actualHeight = maxY - minY + padding * 2;

  let svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     width="${width || actualWidth}"
     height="${height || actualHeight}"
     viewBox="${minX - padding} ${minY - padding} ${actualWidth} ${actualHeight}">
`;

  // Background
  if (backgroundColor !== 'transparent') {
    svg += `  <rect width="100%" height="100%" fill="${backgroundColor}"/>\n`;
  }

  // Edges (draw first so they appear behind nodes)
  edges.forEach((edge) => {
    const sourceNode = nodes.find((n) => n.id === edge.source);
    const targetNode = nodes.find((n) => n.id === edge.target);

    if (!sourceNode || !targetNode) return;

    const sourceX = (sourceNode.position?.x || 0) + (sourceNode.width || 200) / 2;
    const sourceY = (sourceNode.position?.y || 0) + (sourceNode.height || 100) / 2;
    const targetX = (targetNode.position?.x || 0) + (targetNode.width || 200) / 2;
    const targetY = (targetNode.position?.y || 0) + (targetNode.height || 100) / 2;

    // Simple bezier curve
    const midY = (sourceY + targetY) / 2;
    const path = `M ${sourceX} ${sourceY} C ${sourceX} ${midY}, ${targetX} ${midY}, ${targetX} ${targetY}`;

    const stroke = edge.style?.stroke || '#b1b1b7';
    const strokeWidth = edge.style?.strokeWidth || 2;
    const strokeDasharray = edge.style?.strokeDasharray || '';

    svg += `  <path d="${path}"
    stroke="${stroke}"
    stroke-width="${strokeWidth}"
    fill="none"
    ${strokeDasharray ? `stroke-dasharray="${strokeDasharray}"` : ''}/>\n`;
  });

  // Nodes
  nodes.forEach((node) => {
    const x = node.position?.x || 0;
    const y = node.position?.y || 0;
    const w = node.width || 200;
    const h = node.height || 100;
    const label = node.data?.label || node.id || '';
    const bgColor = node.style?.backgroundColor || node.data?.bgColor || '#ffffff';
    const borderColor = node.style?.borderColor || node.data?.borderColor || '#333';
    const borderWidth = node.style?.borderWidth || node.data?.borderWidth || 2;
    const borderRadius = node.style?.borderRadius || 8;

    // Node rectangle
    svg += `  <g transform="translate(${x}, ${y})">
    <rect width="${w}" height="${h}"
          fill="${bgColor}"
          stroke="${borderColor}"
          stroke-width="${borderWidth}"
          rx="${borderRadius}"/>
    <text x="${w / 2}" y="${h / 2}"
          text-anchor="middle"
          dominant-baseline="middle"
          font-family="Arial, sans-serif"
          font-size="14"
          fill="#333">${escapeXml(label)}</text>
  </g>\n`;
  });

  svg += '</svg>';

  return svg;
}

/**
 * Escapes special XML characters
 */
function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * SVG Export Service
 */
export const svgExportService = {
  exportAsSVG,
  exportAndDownloadSVG,
  exportAsSVGWithProgress,
  createPureSVGFromElements,
};
